# permissions for end users to view samples.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: sample1
    app.kubernetes.io/managed-by: kustomize
  name: sample-viewer-role
rules:
- apiGroups:
  - api.raibagi.samples
  resources:
  - samples
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - api.raibagi.samples
  resources:
  - samples/status
  verbs:
  - get
